apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config/default

# Set the image tags to match the git version from above
# https://github.com/ansible/eda-server-operator#readme for git version
images:
  - name: quay.io/ansible/eda-server-operator
    newTag: 1.0.2

# Specify a custom namespace in which to install EDA
namespace: eda
